[project]
name = "multiuav-semcom"
version = "0.1.0"
description = "Task-Oriented Semantic Communication for Multi-UAV Cooperative Tracking"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "djitellopy",
    "matplotlib",
    "numpy",
    "opencv-python",
    "scipy",
    "torch",
    "torchvision",
    "tqdm>=4.68.3",
]
